apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kustom-webapp-prod
  namespace: argocd
spec:
  destinations:
    - namespace: kustom-webapp-prod
      name: "*"
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceNamespaces:
    - "*"
  syncWindows:
    - kind: allow
      schedule: "* 8-17 * * 1-4"
      duration: 1h
      timeZone: Europe/Zurich
      manualSync: true
      applications:
        - "*"
