apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kustom-webapp-preprod
  namespace: argocd
spec:
  destinations:
    - namespace: kustom-webapp-preprod
      name: "*"
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceNamespaces:
    - "*"
  signatureKeys:
    - keyID: 7E243C24EE3BCED2
    - keyID: 043123FF2E8BE320
    - keyID: 508855D4AF4F3E73
