apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxies
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/heig-lherman/cld'
    targetRevision: HEAD
    path: k8s/system/proxy
  destination:
    name: in-cluster
    namespace: gloo-system
