apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/heig-lherman/cld'
    targetRevision: HEAD
    path: k8s/system/sealed-secrets
  destination:
    name: in-cluster
    namespace: system-sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
