apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-gpg-keys-cm
data:
  7E243C24EE3BCED2: |-
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    
    mQINBF+fJeIBEADq/r+IBMcvPmOoYbSxBJLoB8dBm23kyCxyVLPzJIgaweuI6AoO
    FWZCBgYizDT7Uq3UrTOdKPzBSTIMogCBbmVgqRJm4FvBGAEM3PshHRF2cmZQ0Zd7
    4yskLkPmzn6i/i5AUzpwYLnArQY+z1Dw3mk8bVGiZ11LThsPMGpo1TCwfuyOkUyh
    Q4k7wPPmO1gFKiNrvc5iERSjEeatL0qPFfK63cZbINs2zfNG6hksbFPib9yn/DVZ
    LFPFYRrPJATItZ1jUd+YczvqID1rRmKOj4+m9TFQqfyudIN1vPm+9Yyy4OufDIOc
    Si10r5UftQiJwImbpTZF1MZOQsiVUewfMV2JNTLv5yybmfmL5ByV4PxiZZ3qSgEC
    cPWhjPOLqPYVsmZjOTatCbmIcg5iwZEt2QcrxGHCBviFE7kutWVmfct7id9lrwGp
    rZ0u5ZvCYqBLNnmguW+BZ4Hd/v8KE24zoM2Syw2rCL+mAXQCgiIcJNLT5IqC7Gnn
    jZqtFWUtaP7QczSLZE6IyJCQ59uHz1ZFM4MUI7EXO/zrkS7BOTXFp+wdi6qQ6FQQ
    O2qAxEY26KF/40sXxq3tlOCp3FR96nxaj11tCTFt2Nvapfan7bNR91frSz+I9ibG
    wgDKHlyLv5RBf7Pc9pv4WTh3Sz3n0W33cQqtL3Cw+9m9XnMAT0UP/D/b6wARAQAB
    tCFMb8OvYyBIZXJtYW4gPGxvaWNAbG9pY2hlcm1hbi5jaD6JAk4EEwEIADgWIQRW
    gHjWjR0lF0W/NTh+JDwk7jvO0gUCX58l4gIbAwULCQgHAgYVCgkICwIEFgIDAQIe
    AQIXgAAKCRB+JDwk7jvO0j0wEAC8pkmy4g9OqUJ5QgTCo7cLWeAf0gXUYi2rlxQ3
    1cfTBOwIJf3Mc09DIKKPl6cEwAn2nEsDXpK3WxnXyQN96yBaaKj9+z0O0rMuo5PR
    TOtqaubshd/x8DKy0tXNlWYo2HlqzzsjYFzk/QmlN72YmnzIBiCaDocTtEasEZKM
    XyFCEeIdJCBJASRDnYM7QgzzHKIzTv0JEx/pBPeO+1hY97ggXHASdWidpQAiPwmp
    874Aeg/c4cFv9bnFAsDGtr7YTmi1xDY+cIbXk/GkrJPUIliL/Cl+UeDlIecw72GU
    tY4e8f6zBsyNSJjL50YxCvwyvrva9ovdMuzVQCagZYWw5k+yJT/PlJXz0ej7LIiH
    grEBH3WH0Zqhjqcm4VVPIDpvkng9NpycCa/GCe1nqQyrjHz94qi7/mfMpeWYm+UM
    OH4N85Lh8d1dBmI3rLxgoeDERQETFU/8xzIcWiIhLWLBd/b6nJY/JSdaizH6f6+m
    3w8y7r6hrMIxKY1yTR1qL0aGxdt9RhUwXw2WTfxjA+j1yZv9oVJGk4rruQA33mBv
    eMqOuQEdMmUbx7RXMvRu1NnCYCvFzg4+SY1hCb7KjE+hrytRPU1QTsyWOUaUTewN
    XJRJGqbOViFJgNaue1FkyzWRo2jq4EqK/7P6506ITPu8J/aYGB5VzbrH9i/WxUbe
    AV47cbkCDQRfnyXiARAAq06+ErISVJrq/EG4xiE5YydsF9OL0aKr1sFgxrMDQpIc
    oqXwR3B05pUZLBWepJcNUjCFfs0WLqIrwsiWPrsIxgVfUJHoI2NPy5gts5erwOde
    YwcRY5+uHX0wSxvQE8OFjz2HO03b0Ov2Wi3ja8Hpn03CRvdU62Va/Qh5HakcZRJW
    kVO4aom6bHidqlxtTstVmKvyoKD1TrnefKFV47NPuYY06IkJj9VWoccfEWX6QwVN
    qKpkJUeDS87DEft7+yRXPoYprxlUB1jtAqZE2qxDi9tBRIfYE0DE9HNfN6Xl5QEp
    6Dd4dWmM2d01Oau2Hod0XkB5V1HAvwAfycEGlv5PkOFYYv8qC69ol2KTxjIObSj1
    6jOOygVX2fUQucsPOYj1y/HXNS22rZs07mmCPlIQ79J0B0l2bITXXxvUkmV399Xm
    TftNOS/g4uTJkjgZifHL9OTlqDoPwiYnGj91qooPkaPHcI866WyNIN0NMGQYsvwy
    ZPMuO5MlyxSBqLa81Y8J8fpOhKuwJoret/J0pQW28n393rQM0uTp6EXt2R/guOCH
    WUfySSPr5hieKdyFeiHxe/l4TSMbvcE+68NLITgxH9s9i1mQxwrnhUZCcDCh2FBS
    LZ/x9YwBVXN6/u9ClwyFZ8qEp6i3AlWtf8/vMrkSpv3aCiChQlp3CU3cxYwHpP0A
    EQEAAYkCNgQYAQgAIBYhBFaAeNaNHSUXRb81OH4kPCTuO87SBQJfnyXiAhsMAAoJ
    EH4kPCTuO87SPCwP/2pLiQYZ8oU7EIj86dO64Grkv7uQjW6GsyResL7MI+ukndf2
    CBpjFchWh3rT1nJx2uyGU+NNj7U7putbZBHNvzeqZm67xpG70A5nmkNq0q+xY9ka
    Bz459a8Yjk22F7Sy0ccojyVuhfHuG4ea7uwIc9CGOBUmFsWEveaQ1ObTu/usPlRo
    nGhZ3FTm5PRh8dLVbBq4RHtBHvjjmCa2cPALSgAN9yqT8ea7ZG4oGjd3ewmug7Ex
    VPiHw2BhqomQH4OZeoUebahIjWwZqnE4KNrrio+phdUAP82Bmv8OmETOL32N3CcT
    9aMvlBRwDwKTQIbnh8fD63SsGdc29reVyOoowVyL+cJn4oABY7Ci4mlsbXqxc2vo
    S2ekud2Seg0KUB2c4iH5oT7iCrHXl7drSkAuSDL4txTbV2eCr7LXH85XEFiAXkCf
    LcVOCCrOfeRJ+DOjilQhWaEmZhXxumfV5fp8R/SsAWpCKrqLKSv2rKqD2uPlNBSI
    pE+hn+RQsTHg2JTodY7SjO5RnhCIuI5/ma2ijDI0GlswltaAw9NpfG56Eoaw99IK
    FUaqZcSX/EVkRBhTMCvGDMDz9VQv6iiZDVvOfvAW8VaahsTdshds7eMy+d60e4I+
    oOcmOCQjZryoNEvdyKVt6nW7hKuZVBnEGIx+75K7i8DPgtCrjXkK8Dw4TNVz
    =9RFD
    -----END PGP PUBLIC KEY BLOCK-----
