apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # exec in containers
  exec.enabled: 'true'
  admin.enabled: 'true'
  # kustomize requirements
  kustomize.buildOptions: '--enable-helm'
  application.resourceTrackingMethod: 'annotation+label'
  application.instanceLabelKey: 'argocd.argoproj.io/instance'
  # Set app resync to a shorter value (default 180s)
  timeout.reconciliation: '60s'
  # Health monitoring
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
