apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustom-webapp-prod

resources:
- ../../base

commonLabels:
  app-env: prod
  app.kubernetes.io/name: webapp
  app.kubernetes.io/instance: webapp
  app.kubernetes.io/service: webapp
  app.kubernetes.io/managed-by: Kustomize


replicas:
- name: webapp
  count: 3

configMapGenerator:
- name: webapp-config
  env: config.properties