apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.11.2
  - argocd-github-ssec.yaml

  - projects/default-project.yaml
  - projects/kustom-webapp-dev.yaml
  - projects/kustom-webapp-preprod.yaml
  - projects/kustom-webapp-prod.yaml

  - applications/apollo-system.yaml
  - applications/apollo-apps.yaml
  
  - rbac/argocd-server-rbac-crole.yaml
  - rbac/argocd-server-rbac-crb.yaml

patches:
  - path: config/argocd-cm.yaml
  - path: config/argocd-cmd-params-cm.yaml
  - path: config/argocd-gpg-keys-cm.yaml
  - path: config/argocd-ssh-known-hosts-cm.yaml
