apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/heig-lherman/cld'
    targetRevision: HEAD
    path: k8s/apps/home
  destination:
    name: in-cluster
    namespace: apps-home
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
