apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustom-webapp-prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kustom-webapp-prod
  source:
    repoURL: 'https://github.com/heig-lherman/cld'
    targetRevision: HEAD
    path: k8s/apps/kustom-webapp/overlays/prod
  destination:
    name: in-cluster
    namespace: kustom-webapp-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true