apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: todo
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
      component: frontend
  template:
    metadata:
      labels:
        app: todo
        component: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/icclabcna/ccp2-k8s-todo-frontend
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: API_ENDPOINT_URL
              value: http://api-svc:8081
          resources:
            requests:
              cpu: 10m