apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apollo-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/heig-lherman/cld'
    targetRevision: HEAD
    path: k8s/_applications/system
  destination:
    name: in-cluster
    namespace: system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
