apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/heig-lherman/cld'
    targetRevision: HEAD
    path: k8s/_applications/apps
  destination:
    name: in-cluster
    namespace: apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
