apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gloo-system

resources:
  - upstream/home.yaml
  - upstream/kustom-web-app-dev.yaml
  - upstream/kustom-web-app-preprod.yaml
  - upstream/kustom-web-app-prod.yaml
  
  - virtualservice/argocd.yaml
  - virtualservice/home.yaml
  - virtualservice/kustom-web-app-dev.yaml
  - virtualservice/kustom-web-app-preprod.yaml
  - virtualservice/kustom-web-app-prod.yaml
